# -*- coding: utf-8 -*-
"""jiyatask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_21dXTSR3lKNeqpGtFZQ2wW1LGDTFV_3
"""



# @title
import pandas as pd
df = pd.read_csv("/Titanic-Dataset.csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df.shape

df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin'], inplace=True)

df.isnull().sum()

df['Sex'].unique()
df['Pclass'].unique()
df['Embarked'].unique()

df.groupby('Sex')['Survived'].mean()
df.groupby('Pclass')['Survived'].mean()
df.groupby('Embarked')['Survived'].mean()

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_Q', 'Embarked_S']]
y = df['Survived']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predictions
y_pred = model.predict(X_test)

# Accuracy
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report:\n", classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Purples')
plt.title("Titanic Survival Prediction - Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

new_passenger = [[3, 1, 25, 0, 0, 7.25, 0, 1]]  # female, 3rd class
prediction = model.predict(new_passenger)
print("Survived" if prediction[0]==1 else " Not Survived")

import joblib
joblib.dump(model, "titanic_model.pkl")
print("Model saved successfully")